-- 自动生成的表结构配置
local config = {
    ["account"] = {
        table_name = "account",
        fields = {
            ["account_key"] = {
                type = "varchar(20)",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "账号标识",
            },
            ["account_id"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = true,
                default = "nil",
                comment = "账号ID",
            },
            ["players"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "玩家列表数据",
            },
            ["last_login_ip"] = {
                type = "varchar(16)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "最后登录IP",
            },
            ["last_login_time"] = {
                type = "datetime",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "最后登录时间",
            },
            ["device_id"] = {
                type = "varchar(32)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "设备ID",
            },
            ["register_ip"] = {
                type = "varchar(16)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "注册IP",
            },
            ["register_time"] = {
                type = "datetime",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "注册时间",
            },
        },
        primary_keys = {
            "account_key",
        },
        indexes = {
            ["account_key"] = {
                unique = true,
                columns = {
                    "account_key",
                },
            },
            ["uk_account_id"] = {
                unique = true,
                columns = {
                    "account_id",
                },
            },
        },
        non_primary_fields = {
            ["account_id"] = true,
            ["device_id"] = true,
            ["last_login_ip"] = true,
            ["last_login_time"] = true,
            ["players"] = true,
            ["register_ip"] = true,
            ["register_time"] = true,
        },
    },
    ["channel"] = {
        table_name = "channel",
        fields = {
            ["channel_id"] = {
                type = "int",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["messages"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["update_time"] = {
                type = "int",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
        },
        primary_keys = {
            "channel_id",
        },
        indexes = {
        },
        non_primary_fields = {
            ["messages"] = true,
            ["update_time"] = true,
        },
    },
    ["friend"] = {
        table_name = "friend",
        fields = {
            ["player_id"] = {
                type = "int",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "玩家ID",
            },
            ["data"] = {
                type = "text",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "好友数据",
            },
        },
        primary_keys = {
            "player_id",
        },
        indexes = {
        },
        non_primary_fields = {
            ["data"] = true,
        },
    },
    ["global_mail"] = {
        table_name = "global_mail",
        fields = {
            ["mail_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = true,
                default = "nil",
                comment = "邮件ID",
            },
            ["mail_type"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件类型:5=全局邮件",
            },
            ["title"] = {
                type = "varchar(50)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件标题",
            },
            ["content"] = {
                type = "varchar(1000)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件内容",
            },
            ["items"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "附件JSON格式",
            },
            ["create_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "创建时间",
            },
            ["expire_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "过期时间",
            },
        },
        primary_keys = {
            "mail_id",
        },
        indexes = {
            ["idx_create_time"] = {
                unique = false,
                columns = {
                    "create_time",
                },
            },
            ["idx_expire_time"] = {
                unique = false,
                columns = {
                    "expire_time",
                },
            },
        },
        non_primary_fields = {
            ["content"] = true,
            ["create_time"] = true,
            ["expire_time"] = true,
            ["items"] = true,
            ["mail_type"] = true,
            ["title"] = true,
        },
    },
    ["guild"] = {
        table_name = "guild",
        fields = {
            ["id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = true,
                default = "nil",
                comment = "公会ID",
            },
            ["name"] = {
                type = "varchar(32)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "公会名称",
            },
            ["create_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "创建时间",
            },
            ["members"] = {
                type = "text",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "成员列表JSON格式",
            },
            ["applications"] = {
                type = "text",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "申请列表JSON格式",
            },
            ["data"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "公会数据",
            },
            ["is_deleted"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "是否已删除:0=未删除,1=已删除",
            },
        },
        primary_keys = {
            "id",
        },
        indexes = {
            ["uk_name"] = {
                unique = true,
                columns = {
                    "name",
                },
            },
        },
        non_primary_fields = {
            ["applications"] = true,
            ["create_time"] = true,
            ["data"] = true,
            ["is_deleted"] = true,
            ["members"] = true,
            ["name"] = true,
        },
    },
    ["mail"] = {
        table_name = "mail",
        fields = {
            ["id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = true,
                default = "nil",
                comment = "自增ID",
            },
            ["mail_id"] = {
                type = "varchar(20)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件ID",
            },
            ["sender_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "发送者ID,0表示系统邮件",
            },
            ["receiver_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "接收者ID",
            },
            ["mail_type"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件类型:1=系统邮件,2=玩家邮件,3=公会邮件,4=系统奖励邮件,5=全局邮件",
            },
            ["title"] = {
                type = "varchar(50)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件标题",
            },
            ["content"] = {
                type = "varchar(1000)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "邮件内容",
            },
            ["items"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "附件JSON格式",
            },
            ["items_status"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "附件是否已领取:0=未领取,1=已领取",
            },
            ["status"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "邮件状态:0=未读,1=已读",
            },
            ["create_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "创建时间",
            },
            ["expire_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "过期时间",
            },
            ["is_deleted"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "是否已删除:0=未删除,1=已删除",
            },
        },
        primary_keys = {
            "id",
        },
        indexes = {
            ["idx_create_time"] = {
                unique = false,
                columns = {
                    "create_time",
                },
            },
            ["idx_expire_time"] = {
                unique = false,
                columns = {
                    "expire_time",
                },
            },
            ["idx_mail_id"] = {
                unique = true,
                columns = {
                    "mail_id",
                },
            },
            ["idx_receiver_id"] = {
                unique = false,
                columns = {
                    "receiver_id",
                },
            },
        },
        non_primary_fields = {
            ["content"] = true,
            ["create_time"] = true,
            ["expire_time"] = true,
            ["is_deleted"] = true,
            ["items"] = true,
            ["items_status"] = true,
            ["mail_id"] = true,
            ["mail_type"] = true,
            ["receiver_id"] = true,
            ["sender_id"] = true,
            ["status"] = true,
            ["title"] = true,
        },
    },
    ["payment"] = {
        table_name = "payment",
        fields = {
            ["id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = true,
                default = "nil",
                comment = "支付记录ID",
            },
            ["order_id"] = {
                type = "varchar(64)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "订单ID",
            },
            ["player_id"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "玩家ID",
            },
            ["account_id"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "账号ID",
            },
            ["product_id"] = {
                type = "varchar(32)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "商品ID",
            },
            ["amount"] = {
                type = "decimal(10,2)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0.00",
                comment = "支付金额",
            },
            ["currency"] = {
                type = "varchar(8)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "CNY",
                comment = "货币类型",
            },
            ["channel"] = {
                type = "varchar(16)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "支付渠道",
            },
            ["channel_order_id"] = {
                type = "varchar(64)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "渠道订单ID",
            },
            ["status"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "0",
                comment = "支付状态:0=创建,1=处理中,2=成功,3=失败,4=退款",
            },
            ["create_time"] = {
                type = "datetime",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "CURRENT_TIMESTAMP",
                comment = "创建时间",
            },
            ["pay_time"] = {
                type = "datetime",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "支付时间",
            },
            ["ip_address"] = {
                type = "varchar(16)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "支付IP",
            },
            ["device_id"] = {
                type = "varchar(32)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "设备ID",
            },
            ["extra_data"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "额外数据",
            },
        },
        primary_keys = {
            "id",
        },
        indexes = {
            ["idx_account_id"] = {
                unique = false,
                columns = {
                    "account_id",
                },
            },
            ["idx_channel_order"] = {
                unique = false,
                columns = {
                    "channel",
                    "channel_order_id",
                },
            },
            ["idx_create_time"] = {
                unique = false,
                columns = {
                    "create_time",
                },
            },
            ["idx_order_id"] = {
                unique = true,
                columns = {
                    "order_id",
                },
            },
            ["idx_player_id"] = {
                unique = false,
                columns = {
                    "player_id",
                },
            },
        },
        non_primary_fields = {
            ["account_id"] = true,
            ["amount"] = true,
            ["channel"] = true,
            ["channel_order_id"] = true,
            ["create_time"] = true,
            ["currency"] = true,
            ["device_id"] = true,
            ["extra_data"] = true,
            ["ip_address"] = true,
            ["order_id"] = true,
            ["pay_time"] = true,
            ["player_id"] = true,
            ["product_id"] = true,
            ["status"] = true,
        },
    },
    ["payment_log"] = {
        table_name = "payment_log",
        fields = {
            ["id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = true,
                default = "nil",
                comment = "日志ID",
            },
            ["order_id"] = {
                type = "varchar(64)",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "订单ID",
            },
            ["status"] = {
                type = "tinyint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "状态变更",
            },
            ["log_time"] = {
                type = "datetime",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "CURRENT_TIMESTAMP",
                comment = "日志时间",
            },
            ["log_content"] = {
                type = "text",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "日志内容",
            },
            ["operator"] = {
                type = "varchar(32)",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "操作人/系统",
            },
        },
        primary_keys = {
            "id",
        },
        indexes = {
            ["idx_log_time"] = {
                unique = false,
                columns = {
                    "log_time",
                },
            },
            ["idx_order_id"] = {
                unique = false,
                columns = {
                    "order_id",
                },
            },
        },
        non_primary_fields = {
            ["log_content"] = true,
            ["log_time"] = true,
            ["operator"] = true,
            ["order_id"] = true,
            ["status"] = true,
        },
    },
    ["player_odb"] = {
        table_name = "player_odb",
        fields = {
            ["player_id"] = {
                type = "int unsigned",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "玩家ID",
            },
            ["data"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "离线玩家数据",
            },
            ["update_time"] = {
                type = "timestamp",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "CURRENT_TIMESTAMP",
                comment = "更新时间",
            },
        },
        primary_keys = {
            "player_id",
        },
        indexes = {
        },
        non_primary_fields = {
            ["data"] = true,
            ["update_time"] = true,
        },
    },
    ["player_private"] = {
        table_name = "player_private",
        fields = {
            ["player_id"] = {
                type = "int",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["data"] = {
                type = "text",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
        },
        primary_keys = {
            "player_id",
        },
        indexes = {
        },
        non_primary_fields = {
            ["data"] = true,
        },
    },
    ["private_channel"] = {
        table_name = "private_channel",
        fields = {
            ["channel_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["player1_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["player2_id"] = {
                type = "bigint",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["last_message_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
            ["create_time"] = {
                type = "int",
                is_required = true,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "",
            },
        },
        primary_keys = {
            "channel_id",
        },
        indexes = {
            ["idx_last_msg"] = {
                unique = false,
                columns = {
                    "last_message_time",
                },
            },
            ["idx_players"] = {
                unique = false,
                columns = {
                    "player1_id",
                    "player2_id",
                },
            },
        },
        non_primary_fields = {
            ["create_time"] = true,
            ["last_message_time"] = true,
            ["player1_id"] = true,
            ["player2_id"] = true,
        },
    },
    ["ranking"] = {
        table_name = "ranking",
        fields = {
            ["name"] = {
                type = "varchar(32)",
                is_required = true,
                is_primary = true,
                is_auto_increment = false,
                default = "nil",
                comment = "排行榜名称",
            },
            ["data"] = {
                type = "text",
                is_required = false,
                is_primary = false,
                is_auto_increment = false,
                default = "nil",
                comment = "排行榜数据",
            },
        },
        primary_keys = {
            "name",
        },
        indexes = {
        },
        non_primary_fields = {
            ["data"] = true,
        },
    },
}
return config
