
-- 公会职位定义
local GUILD_POSITION = {
    LEADER = 1,      -- 会长
    VICE_LEADER = 2, -- 副会长
    ELDER = 3,       -- 长老
    MEMBER = 4,      -- 普通成员
}

-- 公会权限定义
local GUILD_PERMISSION = {
    DISBAND = 1,           -- 解散公会
    KICK = 2,              -- 踢人
    APPOINT = 3,           -- 任命职位
    MODIFY_NOTICE = 4,     -- 修改公告
    MODIFY_JOIN_SETTING = 5, -- 修改加入设置
    ACCEPT_JOIN = 6,       -- 接受加入申请
    REJECT_JOIN = 7,       -- 拒绝加入申请
    MANAGE_TREASURY = 8,   -- 管理公会仓库
    MANAGE_BUILDING = 9,   -- 管理公会建筑
    MANAGE_TECH = 10,      -- 管理公会科技
}

-- 职位对应的权限
local POSITION_PERMISSIONS = {
    [GUILD_POSITION.LEADER] = {
        GUILD_PERMISSION.DISBAND,
        GUILD_PERMISSION.KICK,
        GUILD_PERMISSION.APPOINT,
        GUILD_PERMISSION.MODIFY_NOTICE,
        GUILD_PERMISSION.MODIFY_JOIN_SETTING,
        GUILD_PERMISSION.ACCEPT_JOIN,
        GUILD_PERMISSION.REJECT_JOIN,
        GUILD_PERMISSION.MANAGE_TREASURY,
        GUILD_PERMISSION.MANAGE_BUILDING,
        GUILD_PERMISSION.MANAGE_TECH,
    },
    [GUILD_POSITION.VICE_LEADER] = {
        GUILD_PERMISSION.KICK,
        GUILD_PERMISSION.APPOINT,
        GUILD_PERMISSION.MODIFY_NOTICE,
        GUILD_PERMISSION.ACCEPT_JOIN,
        GUILD_PERMISSION.REJECT_JOIN,
        GUILD_PERMISSION.MANAGE_TREASURY,
        GUILD_PERMISSION.MANAGE_BUILDING,
        GUILD_PERMISSION.MANAGE_TECH,
    },
    [GUILD_POSITION.ELDER] = {
        GUILD_PERMISSION.MODIFY_NOTICE,
        GUILD_PERMISSION.ACCEPT_JOIN,
        GUILD_PERMISSION.REJECT_JOIN,
        GUILD_PERMISSION.MANAGE_TREASURY,
    },
    [GUILD_POSITION.MEMBER] = {
        -- 普通成员没有特殊权限
    },
}

local MEMBER_DATA_KEYS = {
    ID = 1,
    NAME = 2,
    POSITION = 3,
    LAST_ONLINE_TIME = 4,
}

return {
    GUILD_POSITION = GUILD_POSITION,
    GUILD_PERMISSION = GUILD_PERMISSION,
    POSITION_PERMISSIONS = POSITION_PERMISSIONS,
    MEMBER_DATA_KEYS = MEMBER_DATA_KEYS,
}