#ifndef RECAST_CONSTANTS_H
#define RECAST_CONSTANTS_H

// RecastNavigation常量定义

// 网格构建参数
#define DEFAULT_CELL_SIZE 0.3f
#define DEFAULT_CELL_HEIGHT 0.2f
#define DEFAULT_WALKABLE_SLOPE_ANGLE 45.0f
#define DEFAULT_WALKABLE_HEIGHT 2.0f
#define DEFAULT_WALKABLE_RADIUS 0.6f
#define DEFAULT_WALKABLE_CLIMB 0.9f
#define DEFAULT_MAX_SIMPLIFICATION_ERROR 1.3f

// 系统限制
#define DEFAULT_MAX_TILES 2048
#define DEFAULT_MAX_OBSTACLES 64
#define DEFAULT_MAX_NAV_MESHES 100
#define DEFAULT_MAX_OBSTACLES_PER_MESH 100
#define DEFAULT_NAV_QUERY_MAX_NODES 8192
#define DEFAULT_PATH_MAX_SIZE 1024

// 搜索参数
#define DEFAULT_SEARCH_EXTENTS 30.0f
#define DEFAULT_CHARACTER_HEIGHT 0.0f
#define DEFAULT_MAX_HEIGHT 100.0f

// 过滤参数
#define DEFAULT_WALKABLE_CLIMB_FILTER 2
#define DEFAULT_WALKABLE_HEIGHT_FILTER 2
#define DEFAULT_WALKABLE_RADIUS_ERODE 2

// 区域构建参数
#define DEFAULT_REGION_MIN_SIZE 0
#define DEFAULT_REGION_MERGE_SIZE 2
#define DEFAULT_REGION_MIN_AREA 8

// 轮廓构建参数
#define DEFAULT_CONTOUR_MAX_ERROR 2.0f
#define DEFAULT_CONTOUR_MAX_EDGE_LEN 8

// 多边形网格参数
#define DEFAULT_POLY_MAX_VERTS 6
#define DEFAULT_DETAIL_SAMPLE_DIST 2.0f
#define DEFAULT_DETAIL_SAMPLE_MAX_ERROR 6.0f
#define DEFAULT_POLY_FLAGS 1

// 地形高度定义
#define DEFAULT_TERRAIN_HEIGHT_PLAIN 0.0f
#define DEFAULT_TERRAIN_HEIGHT_WATER -1.0f
#define DEFAULT_TERRAIN_HEIGHT_MOUNTAIN 5.0f
#define DEFAULT_TERRAIN_HEIGHT_OBSTACLE 0.0f
#define DEFAULT_TERRAIN_HEIGHT_SAFE_ZONE 0.0f
#define DEFAULT_TERRAIN_HEIGHT_TRANSPORT 0.0f

// 地形类型定义
#define TERRAIN_TYPE_PLAIN 1
#define TERRAIN_TYPE_WATER 2
#define TERRAIN_TYPE_MOUNTAIN 3
#define TERRAIN_TYPE_OBSTACLE 4
#define TERRAIN_TYPE_SAFE_ZONE 5
#define TERRAIN_TYPE_TRANSPORT 6

#endif // RECAST_CONSTANTS_H 